spring:
  application:
    name: isb-boot-druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rds952kloa0o4wtxf727o.mysql.rds.aliyuncs.com:3306/ju321boot
    username: ju321demo
    password: rj090123
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall