spring:
  application:
    name: isb-boot-zuul
zuul:
  host:
    maxTotalConnections: 100000
    maxPerRouteConnections: 100000
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  eureka:
    isb-common-adapter-in:
      semaphore:
        maxSemaphores: 1000
  routes:
    isb-common-adapter-in:
      path: /anxh/**
      serviceId: isb-common-adapter-in
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000            
server:
  tomcat:
    max-threads: 1024
    min-spare-threads: 64